### ISSUE TITLE
could we get the files in an editable format like fusion360 or step?

### ISSUE THREAD

**Issue by raptordemon** [Nerdiyde/NerDIYs_STLs#1]
first of all fantastic work!! this is amazing.

id like to print this but i need something that is in inches not mm (our duct sizes are 4in 5in 6in and 8in ususally) and id like to modify the parts to fit.

would you be willing to share the sources?
thanks
Raptor

**Comment by Nerdiyde** [comment]
Hey guys,
sorry for the late response. :)
Actually I'm not yet sure if I want to share the sources, sorry. :/

But I made some adapters for different hose-sizes. E.g. this one: https://github.com/Nerdiyde/NerDIYs_STLs/blob/main/STLs/solder_fume_extraction_hose/125mm_to_80mm_hose_adapter_V1.0.stl

I could also prepare some for the desired imperial hose-diameters. Would that be an acceptable compromise? :)

Best regards
Fab

**Comment by raptordemon** [comment]
completely understand! yes a few Imperial hose sizes would absolutely be acceptable! i will see what i have in the workshop and comment back. thank you

**Comment by Nerdiyde** [comment]
Sounds good. :) Let me know which sizes you need :)
Best regards
Fab

**Comment by Nerdiyde** [comment]
> completely understand! yes a few Imperial hose sizes would absolutely be acceptable! i will see what i have in the workshop and comment back. thank you

Hey, I know this is a long time ago problem but I restarted this project and it will also contain all kind of adapters. You can find all the information here: https://hackaday.io/project/195522-printairpipe-printable-air-duct-system

**Comment by raptordemon** [comment]
thanks, i ended up needed 6in and 4in adapters. for the 4in i found one i could buy and the 6in i found one on printables
